### ISSUE TITLE
Add travis test

### ISSUE THREAD

**Issue by wkentaro** [amazon-picking-challenge/apc_common#4]
Could you please add travis-ci for this repository?
@amazon-picking-challenge/admins

**Comment by wkentaro** [comment]
@dpsolomon Could you please do this? 
I have tested it on my repo, and the test passed.
https://github.com/wkentaro/apc_common/pull/1

**Comment by wkentaro** [comment]
ping

**Comment by dpsolomon** [comment]
I allowed Travis access to the APC organization, and just confirmed that it
was active. Do I need to do something specific with apc_common ?

**Comment by wkentaro** [comment]
> I allowed Travis access to the APC organization, and just confirmed that it

Actually, it gives access to setup travis for only the users who has the admin rights.
(I have write access rights but don't have admin rights for apc_common repository)
![image](https://cloud.githubusercontent.com/assets/4310419/14031976/04b46f5a-f253-11e5-93f6-4b1cc5dc9be5.png)

So I'd like someone who has the admin rights to setup travis for this repository.
1. Go to https://travis-ci.org/
2. Press '+' button next to 'My repositories'
3. Select amazon-picking-challenge organization
4. Activate amazon-picking-challenge/apc_common

**Comment by wkentaro** [comment]
@dpsolomon Could you please do this?

**Comment by dpsolomon** [comment]
Got it. Done. Let me know if it works, or if I need to change any settings on travis for this CI instance.

**Comment by wkentaro** [comment]
@dpsolomon Thank you! It is enabled now. https://github.com/amazon-picking-challenge/apc_common/pull/13

**Comment by wkentaro** [comment]
The test has passed. https://github.com/amazon-picking-challenge/apc_common/pull/13
